### PR TITLE
CallbackCache: simplify calling function/method

### PR DESCRIPTION
**Pull request by marc-mabe**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Simplified calling the underlying function/method of CallbackCache (and ObjectCache and ClassCache)

### CODE REVIEW

**Comment by boesing** [comment]
LGTM so far.
Thanks for contributing this!
I'll merge this when I've implemented GHA for CI.
For more details, see laminas/technical-steering-committee#61

**Review by snapshotpl — APPROVED** [review]

**Comment by boesing** [comment]
Hm, I was wondering if I could backport this to v2 but actually, this is a BC break.
I've implemented GHA already and it turns out that changing the callback to `[$className, $method]` changes its type from `string` to `array` and thus, leads to an error when the `callback key` is generated.

https://github.com/laminas/laminas-cache/pull/63/files#diff-affcf97709fa42da6b51246d0e1d19dfbd80479d3cfbf2c35eecae7358107e6dR63 
https://github.com/laminas/laminas-cache/blob/15e0b44324a1dae500648ca78bd56e8671565661/src/Pattern/ClassCache.php#L99

I will rebase this PR against 3.0.x as it contains GHA so we can see the failing tests in here.

**Comment by boesing** [comment]
Wait what? I've tried to rebase against 2.12.x but that led into failing tests.
Why the heck isn't that the case in 3.0.x - I am confused...

---

Okay, somehow the names of the test classes changed due to some of the changes made back in february. I've fixed that with #103 and rebased against 3.0.x now.

**Comment by marc-mabe** [comment]
@boesing should be fine now

**Comment by boesing** [comment]
Thanks, Marc. 
Looks good. As far as I can see, this wont be a BC break, right?
I'll probably retarget this against 2.12.x if its not considered BC break so we get this out of the door somewhen in the next weeks rather than months.
WDYT?

**Review by boesing — APPROVED** [review]

**Comment by marc-mabe** [comment]
I don't see any bc break here. It's just an internal optimisation.

**Comment by boesing** [comment]
GHA have major outage as of https://www.githubstatus.com/incidents/zbpwygxwb3gw

Verified functionality locally on all three PHP versions.
Thanks, @marc-mabe!

**Pull request merged**
