### PR TITLE
Mark `ClassCache` pattern as deprecated

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

As recommended by @marc-mabe in #107, we mark the `ClassCache` as deprecated as of v2.12.

### CODE REVIEW

**Comment by marc-mabe** [comment]
It should be marked as deprecated in documentation as well : https://github.com/laminas/laminas-cache/blob/2.12.x/docs/book/pattern/class-cache.md

**Comment by marc-mabe** [comment]
Probably also trigger a deprecation notice on class loading or initializing ?

**Comment by boesing** [comment]
Ive thought it would be a good thing as well when introducing the new Interfaces for plugins but there, the notice was only triggered when upstream did not implemented the `AbstractStorage`. In this case, it would trigger like always as it is a manual pick.

There were some complaints from @Ocramius about having runtime effects in deprecations and thus I try to avoid these now as I see the point. 
Since the class will only be removed in the next major, I think it will be fine. Updating to a new major should be a process where the migration documentation should be used and thus I have to add this there. 

Actually, there is not even an alternative to this and thus no way of fixing the deprecation message unless someone copys the code and removes the message.

What do you think?

**Comment by marc-mabe** [comment]
Fine for me. At least the current documentation and (upcoming) migration guide should include this deprecation/removal.

**Comment by boesing** [comment]
@froschdesign Is there some "standard" to mark something as deprecated in the documentation?

**Comment by froschdesign** [comment]
@boesing 
We use a blockquote for this. Example:

``````
# ClassCache

> ### Deprecated
>
> The `ClassCache` pattern is deprecated…
``````

The block should be placed directly after the headline. It would be good if an alternative with a link could be added.

**Comment by boesing** [comment]
@froschdesign Sadly, there is no alternative yet. I am thinking about creating a pattern which can be used in combination with PSR-6 to have such cache logic again but that is not yet implemented.

**Pull request merged**
