### PR TITLE
Update to use PHP 8.1 syntax

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since composer.json require php 8.1, php 8.1 syntax can be applied.

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready for review 👍 Test failure is unrelated, as I tested equal result in 4.1.x

```
➜  laminas-cache git:(4.1.x) vendor/bin/phpunit test/Psr/CacheItemPool/CacheItemTest.php
PHPUnit 9.6.21 by Sebastian Bergmann and contributors.

......F...F                                                       11 / 11 (100%)

Time: 00:00.012, Memory: 6.00 MB

There were 2 failures:

1) LaminasTest\Cache\Psr\CacheItemPool\CacheItemTest::testExpiresAfterInt
Failed asserting that 7200 matches expected 3600.

/Users/samsonasik/www/laminas/laminas-cache/test/Psr/CacheItemPool/CacheItemTest.php:89

2) LaminasTest\Cache\Psr\CacheItemPool\CacheItemTest::testClockProvidedDoesNotContainUTCTimeZone
Failed asserting that 7200 matches expected 3600.

/Users/samsonasik/www/laminas/laminas-cache/test/Psr/CacheItemPool/CacheItemTest.php:147
```

**Comment by gsteel** [comment]
Can you try a rebase here please @samsonasik ?

**Comment by samsonasik** [comment]
@gsteel rebased 👍

**Review by froschdesign — APPROVED** [review]

**Review by gsteel — APPROVED** [review]
Thanks @samsonasik 👍

**Pull request merged**
