### PR TITLE
Allow installation on PHP 8.1

### PR DESCRIPTION
**Pull request by cedric-anne**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Allow installation on PHP 8.1 for 2.13.x version.

### CODE REVIEW

**Comment by froschdesign** [comment]
@cedric-anne 
The support for PHP 8.1 is already added for version 3.0.0 (#165). Because of the adapters, it is not possible to simply raise the version, a _little more_ work is needed.

**Comment by boesing** [comment]
V3 will be released with PHP 8.1 and thus, you can migrate `laminas-cache` to v3 when you want to upgrade to PHP 8.1

**Comment by boesing** [comment]
I would be open for a 2.14.0 version to provide support for PHP 8.1 on the 2.x series.
Depending on that, those cache adapters which are not yet already marked abandoned (and thus won't receive any PHP 8.1 support) can also provide support for PHP 8.1 in their 1.x series.

But I personally won't work on that as I dont have time for this.
I can provide a new 2.14.x branch for that but anything more than providing PHP 8.1 won't be merged to the 2.x series anymore.

Users which do want to use PHP 8.1 on the 2.x series of this component have to use composer magic (e.g. `replace`) to remove those adapters which won't receive any more updates:

https://github.com/laminas/laminas-cache/tree/2.13.x#example-composerjson-with-only-memory-adapter-being-installed

**Comment by froschdesign** [comment]
@boesing 
Version 3.0.0 should be the next step, a second theatre is not necessary.

**Comment by boesing** [comment]
@froschdesign after seeing that the StorageFactory is used in other components, I think that will be necessary as I dont see a way for an easy migration path which is a major requirement for me. even tho Users migrate their code to 3.0 cache, all other laminas components which do suggest laminas-cache while using StorageFactory wont be able to migrate to v3 and thus are actually conflicting. 

This will lead to crashes and stuff.

I wish that wont be necessary but I think we will use Users when we do not provide a smooth upgrade path.

**Comment by froschdesign** [comment]
@boesing 
I can remove the usage with the storage factory from laminas-i18n. Would that help?

**Comment by boesing** [comment]
@froschdesign how would you do that without adding BC break?

**Comment by froschdesign** [comment]
@boesing 
Using the current replacement of `Laminas\Cache\StorageFactory`. Is there an appropriate replacement?

**Comment by boesing** [comment]
@froschdesign no, as the replacement has to be fetched via container. 

https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/2.0.x/src/Filesystem/AdapterPluginManagerDelegatorFactory.php

**Comment by cedric-anne** [comment]
@boesing 

I started to work on PHP 8.1 support on a 2.14.x branch of laminas-cache component and on 1.x series of adapter.
As adapters are requiring the main laminas-cache component which is also requiring adapters itslef, I had to force usage of my forks in each composer.json to be able to pass CI tests.

For now, I just worked on the memory adapter itself.
Related commits are:
https://github.com/cedric-anne/laminas-cache-storage-adapter-memory/commit/070331dff09af24f7486478569e9f5314665c4c5
https://github.com/cedric-anne/laminas-cache-storage-adapter-test/commit/ecb12f1eb420a669347dbcf0fcce494fd6e71bea
https://github.com/cedric-anne/laminas-cache/commit/2799019a41032044a6df9c905f7a15eb339c0186

All changes in `composer.json` files have to be revert, except the one related to PHP `~8.1.0` requirement. Problem is that it is actually not possible to have CI tets passing without these.

So, how should I organize my PRs ? I could split them into 2 commit. A first one, that could be cherry-picked after valdiation, with legitimate changes, and a second one, that would not be merged, with changes only used to force usage of forks.

**Pull request closed without merging**
