### PR TITLE
Add suppport for `psr/cache` v2 and v3

### PR DESCRIPTION
**Pull request by jguittard**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | not yet
| New Feature   | yes

### Description

This adds support for `psr/cache` v2 and v3.

### CODE REVIEW

**Comment by boesing** [comment]
The update of `psr/cache` is still blocked by several packages.
Please run the following commands to see why this change currently makes no sense:
- `composer why-not psr/cache 2.0`
- `composer why-not psr/cache 3.0`

If the packages listed in the output do support `psr/cache` v2 & v3, you will see that tests are failing due to the imcompatibility of the `psr/cache` implementation in this repository.
Just bumping `composer.json` won't be enough.

**Comment by boesing** [comment]
I've created a new release of `laminas/laminas-cache-storage-adapter-test` to allow `dev-master` of `cache/integration-tests`.
That component did not receive any new release for over a year now but `dev-master` removed some dependencies which seem not to be required 🤷🏼‍♂️ 

With this being done, the fun part can begin because the `CacheItemPoolDecorator` has to become compatible for v2 and v3 without breaking compatibility to v1 to avoid a new major here.

**Comment by boesing** [comment]
Update: Had to update some more dependencies to actually provide support for PHP 8.1 without ignoring platform requirements.

I think the current state of this branch is a good starting point to provide support for both `psr/cache` v2 & v3.

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Comment by mrVrAlex** [comment]
Hi! 
What are we waiting on this?

**Comment by Ocramius** [comment]
I think this is ready? WDYT, @boesing? Blockers/dependencies?

**Comment by boesing** [comment]
Tests are failing. I just fixed this PR after the initial creation to show that the changes which were made are not enough to mark this component as "compatible with `psr/cache` v3".

So until the tests are not passing, we can not merge this.

**Comment by Ocramius** [comment]
Totally missed that, sorry 🤦

**Comment by rimvislt** [comment]
Currently working on project migration to php8.1 and I hope this soon will be merged into branch because got composer conflicts with **"- symfony/cache[v6.0.0, ..., v6.1.3] require psr/cache ^2.0|^3.0 -> found psr/cache[2.0.0, 3.0.0]"**  and I need minimum symfony/cache: v6  - to support php8.1.   For now just getting this code from **"jguittard/laminas-cache"** because it is no other way to get it running on php8.1 with symfony/cache.

**Comment by Ocramius** [comment]
@rimvislt just beware that you are running on broken shells until the build is green.

You can also rebase + fix any failures here, if you want to help out.

**Comment by rimvislt** [comment]
Fixed in pr https://github.com/laminas/laminas-cache/pull/216

**Comment by Fahl-Design** [comment]
any updates on this?

**Comment by ayurenia-seedbox** [comment]
Hello, 
any updates on this?
thanks

**Comment by boesing** [comment]
Closing in favor of #275

**Pull request closed without merging**
