### PR TITLE
PHP 8.2 support, drop PHP 7.4 support

### PR DESCRIPTION
**Pull request by Ocramius**
This is a follow-up of #230 (rebased and with `ext-apcu` installed).

@fezfez did most of the work, I just provided it as alternate PR due to push to fork not being enabled :)

### CODE REVIEW

**Comment by fezfez** [comment]
already done https://github.com/laminas/laminas-cache/pull/230 :s

**Comment by Ocramius** [comment]
Iz fine, at least we're validating each other's work :P

**Comment by Ocramius** [comment]
:ship: here meanwhile - will auto-close #230

**Comment by fezfez** [comment]
> Iz fine, at least we're validating each other's work :P

yep :p

**Pull request merged**
